### ISSUE TITLE
Values object must be immutable

### ISSUE THREAD

**Issue by MuntzMathias** [michael-rubel/laravel-value-objects#13]
According to the principles of DDD, Values object must be immutable, but here the constructor are public. So i can easily do this.

```php
$test = new Text('value1');
$test->__construct('value2');

echo $test->value; // value2
```

Shouldn't you protect this method, and make it call from a static method like `ValueObject::new($value)` ?

**Comment by michael-rubel** [comment]
The objects are immutable, but not in the constructor.

If you try to assign a value manually, it will throw an exception:
```php
$test = new Text('value1');

$test->value = 'new value'; // ... Exception
```

I considered making constructors `final`, but this way developers are limited in extending objects/overriding the constructor logic, e.g. `Name` extends `Text` and adds sanitization logic. With `final` construct we'll be unable to do that.

**Comment by MuntzMathias** [comment]
I would have simply put the constructor in protected so that the developers cannot use it without passing a static method which will act as a factory.

```php
protected function __construct(string|Stringable $value)
{
    // ....
}

public static function make(mixed ...$values): static
{
    return new static(...$values);
}
```
