### ISSUE TITLE
Laravel v11.21.0 - fireAfterResolvingAttributeCallbacks method

### ISSUE THREAD

**Issue by davideprevosto** [michael-rubel/laravel-value-objects#48]
Hi there, since yesterday I'm getting the following error:

`Method App\Application::fireAfterResolvingAttributeCallbacks does not exist.`

It looks like the Laravel team added the following method into `src/Illuminate/Container/Container.php`

```
public function fireAfterResolvingAttributeCallbacks(array $attributes, $object)
    {
        foreach ($attributes as $attribute) {
            if (is_a($attribute->getName(), ContextualAttribute::class, true)) {
                $instance = $attribute->newInstance();

                if (method_exists($instance, 'after')) {
                    $instance->after($instance, $object, $this);
                }
            }

            $callbacks = $this->getCallbacksForType(
                $attribute->getName(), $object, $this->afterResolvingAttributeCallbacks
            );

            foreach ($callbacks as $callback) {
                $callback($attribute->newInstance(), $object, $this);
            }
        }
    }
```

I've investigated a bit and (if I am not wrong) the `michael-rubel/laravel-enhanced-container` package is overriding that class, so the `fireAfterResolvingAttributeCallbacks` method is missing.

I hope I was enough clear and on the right way.

**Comment by michael-rubel** [comment]
Hi @davideprevosto ✋ 

I'm on it. It seems it's time to patch the container.

**Comment by michael-rubel** [comment]
@davideprevosto Please, run the `composer update` and let me know if the problem disappeared. It should update the underlying `laravel-formatters`, and `laravel-enhanced-container` packages. The value objects package itself stays unchanged.

**Comment by davideprevosto** [comment]
@michael-rubel the error disappeared after running composer update. Thank you for your fast response.
